Settings_max_panels_per_transformer = 48
Settings_debug_timing = false
Settings_debug_window = false -- Recommend switching to 30fps if you turn this on
Settings_60fps = true -- if false, 30fps
Settings_cheat_lotsofmoney = false
Settings_cow_speed = 1
Settings_start_money = 0
Settings_start_panels = 1
Settings_start_transformers = 1
Settings_start_wire = 10
Settings_max_selection_range = 2.5
Settings_selection_speed = 12
Settings_axeswings_fullsizetree = 10
Settings_axeswings_youngtree = 5
Settings_axeswing_speed = 11
Settings_axe_min_dist = 1.5